mongo1:
  hostname: mongo1
  image: 'mongo:4.2'
  ports:
    - '27017:27017'

redis1:
  hostname: redis1
  image: 'hpess/redis:master'
  privileged: true
  ports:
    - '6379:6379'

sentinel1:
  environment:
    - master_name=redis1
  hostname: sentinel1
  image: 'hpess/redis:master'
  links:
    - redis1
  privileged: true
  restart: always
  ports:
    - '26379:26379'
